-- SQL Script
-- Created on 15/05/2025 by querzion

-- Write your SQL queries below:
-- STATUSES AND TAGS GENERATED BY AI
INSERT INTO Statuses (StatusName, Description) VALUES
     ('Scheduled', 'The event is officially scheduled and upcoming.'),
     ('Postponed', 'The event has been delayed and will be rescheduled.'),
     ('Cancelled', 'The event has been officially cancelled.'),
     ('Completed', 'The event has successfully concluded.'),
     ('In Progress', 'The event is currently happening.'),
     ('Draft', 'The event is being planned and is not yet published.'),
     ('Awaiting Approval', 'The event is awaiting administrative review.'),
     ('Published', 'The event is publicly visible and available.'),
     ('Sold Out', 'All tickets for this event have been sold.'),
     ('Archived', 'The event is over and has been archived.');

INSERT INTO Tags (TagName, Description) VALUES
      ('Music', 'Events featuring live or recorded music.'),
      ('Technology', 'Tech-related conferences, expos, or meetups.'),
      ('Health & Wellness', 'Fitness, meditation, and health education events.'),
      ('Education', 'Lectures, workshops, and seminars for learning.'),
      ('Business', 'Corporate, networking, and professional events.'),
      ('Sports', 'Games, tournaments, and athletic events.'),
      ('Art', 'Galleries, exhibits, and art-focused events.'),
      ('Food & Drink', 'Culinary experiences, tastings, and food festivals.'),
      ('Community', 'Local community events and public gatherings.'),
      ('Charity', 'Fundraisers and nonprofit-related events.'),
      ('Fashion', 'Fashion shows and style-focused events.'),
      ('Film', 'Screenings, festivals, and movie-related events.'),
      ('Travel', 'Tourism and destination-based events.'),
      ('Startup', 'Entrepreneurship and startup-focused gatherings.'),
      ('Literature', 'Book readings, poetry slams, and literary discussions.'),
      ('Environment', 'Events promoting sustainability and environmental awareness.'),
      ('Gaming', 'Video game tournaments and gaming conventions.'),
      ('Family', 'Kid-friendly or family-oriented activities.'),
      ('Nightlife', 'Parties, club events, and nightlife entertainment.'),
      ('Theater', 'Plays, performances, and dramatic arts events.');

INSERT INTO Locations (Id, StreetName, StreetNumber, PostalCode, City, County, Country) VALUES
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Maple Avenue', '101', '90210', 'Beverly Hills', 'Los Angeles', 'USA'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Baker Street', '221B', 'NW16XE', 'London', 'Greater London', 'UK'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Rue de Rivoli', '99', '75001', 'Paris', 'Île-de-France', 'France'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Alexanderplatz', '5', '10178', 'Berlin', 'Berlin', 'Germany'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Via Roma', '45', '00185', 'Rome', 'Lazio', 'Italy'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Gran Vía', '23', '28013', 'Madrid', 'Madrid', 'Spain'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'George Street', '18A', '2000', 'Sydney', 'New South Wales', 'Australia'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Kingston Road', '89', 'M4C1Z5', 'Toronto', 'Ontario', 'Canada'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Västra Hamngatan', '16', '41117', 'Gothenburg', 'Västra Götaland', 'Sweden'),
     (SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
      SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21), 
      'Ringstraße', '30', '1010', 'Vienna', 'Vienna', 'Austria');

INSERT INTO Events (
    Id, EventName, Description, StartDate, EndDate, CreatedAt, UpdatedAt, IsActive, IsPublic,
    LocationId, TicketInfoId, TagId, StatusId
) VALUES (
             -- Generate a GUID for Id
             SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
             SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
             SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
             SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
             SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),

             'Spring Festival',                      -- EventName
             'A fun community spring festival.',    -- Description
             '2025-05-01',                          -- StartDate
             '2025-05-03',                          -- EndDate
             CURRENT_TIMESTAMP,                     -- CreatedAt
             NULL,                                 -- UpdatedAt
             1,                                    -- IsActive (true)
             1,                                    -- IsPublic (true)

             'existing-location-guid-1',            -- LocationId (replace with actual GUID from LocationEntity)
             'existing-ticketinfo-guid-1',          -- TicketInfoId (replace with actual GUID from TicketInfoEntity)
             2,                                    -- TagId (assuming Tag 2 exists)
             1                                     -- StatusId (assuming Status 1 exists, e.g., 'Scheduled')
         );

INSERT INTO TicketInfos (Id, TicketsTotal, PricePerTicket, TicketsSold, TicketsLeft) VALUES
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          100, 25.00, 0, 100
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          150, 45.50, 0, 150
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          200, 10.00, 0, 200
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          75, 60.00, 0, 75
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          300, 5.00, 0, 300
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          250, 12.75, 0, 250
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          500, 3.50, 0, 500
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          400, 20.00, 0, 400
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          600, 8.25, 0, 600
      ),
      (
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 1, 8) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 9, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 13, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 17, 4) || '-' ||
          SUBSTR(LOWER(HEX(RANDOMBLOB(16))), 21),
          1000, 15.00, 0, 1000
      );